In [1]:
import math
import numpy as np

In [2]:
p1 = [128,379]
p2 = [86, 358]
p3 = [64, 346]


In [4]:
V21 = np.array(p1) - np.array(p2)
V23 = np.array(p3) - np.array(p2)
print(V21,V23)

[42 21] [-22 -12]


In [5]:
V21norm = np.linalg.norm(V21)
V23norm = np.linalg.norm(V23)
inner_prod = np.inner(V21, V23)

print(V21norm, V23norm, inner_prod)

46.95742752749558 25.059928172283335 -1176


In [11]:
cos_theta = inner_prod / ( np.ceil(V21norm * V23norm) )
print(inner_prod, np.ceil(V21norm* V23norm) )
#print(cos_theta)
theta=math.degrees(math.acos(cos_theta))

print(cos_theta, theta)

-1176 1177.0
-0.9991503823279524 177.63799859125788


In [1]:
import svm_5feature

print(X)

NameError: name 'X' is not defined

In [ ]:
[[-0.87362476 -0.225593   -1.         -0.97830724]
 [ 0.225593   -0.11724793 -0.29004364 -1.        ]
 [ 0.52295261 -0.32043487  0.398359   -0.98137938]
 [ 0.30683494 -0.19927508 -0.0792695  -0.84408388]
 [-0.02647013 -0.27970853 -0.6420473  -0.88040258]
 [ 0.56691191 -0.287006    0.48601661 -0.92627391]
 [ 0.26151753  0.01195674 -0.11072272 -0.99869104]
 [ 0.29362598 -0.02146504 -0.84275624 -0.95150888]
 [ 0.52381021 -0.32165291  0.4190365  -1.        ]
 [ 0.53790207 -0.13252838 -0.55955421 -0.99933491]
 [ 0.14323897 -0.30021174 -0.971476   -0.9991638 ]
 [-0.44640744 -0.69922421 -0.78771805 -0.93053482]
 [-0.6256929  -0.731333   -0.99437512 -0.98492726]
 [-0.57231715 -0.66043419 -0.99912363 -0.97100474]
 [-0.14334515 -0.6620395  -0.91239816 -0.97465722]
 [-0.01660528 -0.46140714 -0.81708787 -0.98517546]
 [-0.87910306 -0.6639128  -1.         -0.99115588]
 [-0.57231715 -0.66043419 -0.99912363 -0.97100474]
 [-0.11911213 -0.38391971 -0.81904692 -0.99988107]
 [-0.46967605 -0.84401785 -0.98881769 -0.99376743]
 [-0.24120792 -0.48402179 -0.98473324 -0.94450174]
 [-0.60725493 -0.84700836 -0.97266045 -0.99963076]
 [ 0.22867259 -0.22542695 -0.84408388 -0.66603956]
 [ 0.37401017 -0.02368009 -0.98930809 -0.84916844]
 [ 0.34580079  0.07401022 -0.83496606 -0.59567958]
 [ 0.9443204  -0.33004159 -0.99902859 -0.0419229 ]
 [ 0.22867259 -0.22542695 -0.84408388 -0.66603956]
 [ 0.22134576  0.01257805 -0.89218831 -0.54497007]
 [-0.82552862  0.09620526 -1.          0.09606812]
 [ 0.22243274 -0.24844979 -0.13769108  0.0729396 ]
 [ 0.9443204  -0.33004159 -0.99902859 -0.0419229 ]
 [ 0.86276905  0.71176819 -0.99986172 -1.        ]
 [ 0.71473347  0.5318424  -0.99375761 -0.97802717]
 [ 0.79698558  0.56982687 -0.99912363 -0.99267959]
 [ 0.61101907  0.48432092 -0.98612404 -0.99996107]
 [ 0.74553128  0.53321001 -0.97994925 -0.9927296 ]
 [ 0.83213524  0.72950276 -0.98680497 -0.99978038]
 [ 0.81079038  0.60648132 -0.99437512 -0.99708333]
 [ 0.84010837  0.64132184 -0.98931536 -0.99176476]
 [ 0.68633856  0.4931148  -0.99955144 -0.99032155]
 [ 0.88351601  0.63617378 -0.99951918 -0.99675096]
 [ 0.44894358 -0.09791246 -0.54454136 -0.96237781]
 [ 0.51644575  0.06968296 -0.77641992 -0.84346614]
 [ 0.53816703  0.25898488 -0.59864705 -0.88086285]
 [ 0.4963596  -0.18617078  0.32742272 -0.9208256 ]
 [ 0.52295261  0.06198973  0.48070152 -0.71320949]
 [ 0.09791246  0.08138803 -0.76306372 -0.89148166]
 [ 0.4056037   0.10639191 -0.90193129 -0.97305867]
 [ 0.45792762  0.00834684 -0.99981121 -0.84355373]
 [ 0.59097485  0.36373217 -0.11162143 -0.21575113]
 [ 0.57522974  0.28286634 -0.35204809 -0.37186822]]

In [ ]:
correct label are [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3
 3 3 3 3 4 4 4 4 4 4 4 4 4 4]
predictions are   [0 0 0 0 0 0 0 4 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3
 3 3 3 3 0 4 4 0 0 4 4 4 4 4]